# Generated by Django 3.1.4 on 2021-01-02 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='pincode',
            new_name='zipcode',
        ),
    ]
